study_prefix = "catalog_experimental"

[sql_config]

file_names = [
    "umls_prereq.sql",
    "icd10_tree.sql",
    "icd10_cohort.sql",
    "icd10_cohort_code.sql",
    "icd10_cohort_category.sql",
    "icd10_cohort_block.sql",
    "icd10_cohort_chapter.sql",
    "lab_tree.sql",
    "lab_cohort.sql"
]

# TODO: import Opioid table builders
#[table_builder_config]
#file_names = [
#    "static_builder.py",
#    "rxnorm_valueset_builder.py",
#    "additional_rules_builder.py",
#    "excluded_rules_builder.py",
#]

use_dedicated_schema="catalog"
