study_prefix = "catalog"

[file_config]
file_names = [
    "catalog/icd10_annotated_counts.py",
    "catalog/meta.sql",
]


[export_config]
annotated_count_list = [
    "catalog__count_icd10_all",
    "catalog__count_icd10_chapter",
    "catalog__count_icd10_block",
    "catalog__count_icd10_category",
    "catalog__count_icd10_subcategory_1",
    "catalog__count_icd10_subcategory_2",
    "catalog__count_icd10_subcategory_3",
    "catalog__count_icd10_extension",
]

meta_list = [
    "meta_version",
    "meta_date"
]
