study_prefix = "catalog"

[file_config]
file_names = [
    "catalog/icd10_annotated_counts.py",
    "catalog/meta.sql",
]


[export_config]
annotated_count_list = [
    "catalog__count_icd10_diagnoses"
]

meta_list = [
    "meta_version",
    "meta_date"
]
