-- noqa: disable=all
-- This sql was autogenerated as a reference example using the library
-- CLI. Its format is tied to the specific database it was run against,
-- and it may not be correct for all databases. Use the CLI's build 
-- option to derive the best SQL for your dataset.

-- ###########################################################

CREATE TABLE catalog__icd10_cohort AS
WITH
    icd10 AS (
        SELECT DISTINCT
            code,
            code_display,
            subject_ref,
            encounter_ref
        FROM core__condition
        WHERE system = 'http://hl7.org/fhir/sid/icd-10-cm'
    ),
cohort AS (

    SELECT 
        tree.cui1,
        tree.cui2,
            tree.depth,
            icd10.code,
            icd10.code_display,
            p.gender,
            p.race_display,
            p.ethnicity_display,
            e.age_at_visit,
            e.class_code,
            e.servicetype_display,
            icd10.subject_ref,
            icd10.encounter_ref
    FROM
            icd10,
            core__encounter AS e,
            core__patient AS p,
            umls.icd10_tree AS tree
    WHERE
        icd10.code = tree.code
        AND icd10.encounter_ref = e.encounter_ref
        AND icd10.subject_ref = p.subject_ref


)
SELECT DISTINCT
    cui1,
    cui2,
    
        code,
        code_display,
    
    class_code,
    servicetype_display,
    age_at_visit,
    gender,
    race_display,
    ethnicity_display,
    subject_ref,
    encounter_ref
FROM cohort

-- ###########################################################

CREATE TABLE catalog__icd10_cohort_category AS
WITH
cohort AS (

    SELECT 
        tree.cui1,
        tree.cui2,
            tree.code AS icd10_category,
            concat('(', tree.code, ') ', tree.str) AS icd10_category_display,
            substring(c.code,1,3) as code_start,
            c.code AS icd10_code,
            c.class_code,
            c.servicetype_display,
            c.age_at_visit,
            c.gender,
            c.race_display,
            c.ethnicity_display,
            c.subject_ref,
            c.encounter_ref
    FROM
            catalog__icd10_cohort AS c,
            umls.icd10_tree AS tree


)
SELECT DISTINCT
    cui1,
    cui2,
    
        icd10_code,
        icd10_category,
        icd10_category_display,
    class_code,
    servicetype_display,
    age_at_visit,
    gender,
    race_display,
    ethnicity_display,
    subject_ref,
    encounter_ref
FROM cohort
    WHERE
        icd10_category = code_start

-- ###########################################################

CREATE TABLE catalog__icd10_cohort_block AS
WITH
cohort AS (

    SELECT 
        tree.cui1,
        tree.cui2,
            tree.code AS icd10_block,
            tree.str AS icd10_block_display,
            c.icd10_category,
            c.icd10_code,
            c.class_code,
            c.servicetype_display,
            c.age_at_visit,
            c.gender,
            c.race_display,
            c.ethnicity_display,
            c.subject_ref,
            c.encounter_ref
    FROM
            catalog__icd10_cohort_category AS c,
            umls.icd10_block AS tree
    WHERE
        c.cui1 = tree.cui2


)
SELECT DISTINCT
    cui1,
    cui2,
    
        icd10_code,
        icd10_block,
        icd10_block_display,
    class_code,
    servicetype_display,
    age_at_visit,
    gender,
    race_display,
    ethnicity_display,
    subject_ref,
    encounter_ref
FROM cohort

-- ###########################################################

CREATE TABLE catalog__icd10_cohort_chapter AS
WITH
cohort AS (

    SELECT 
        tree.cui1,
        tree.cui2,
            tree.code AS icd10_chapter,
            tree.str AS icd10_chapter_display,
            c.icd10_block,
            c.icd10_code,
            c.class_code,
            c.servicetype_display,
            c.age_at_visit,
            c.gender,
            c.race_display,
            c.ethnicity_display,
            c.subject_ref,
            c.encounter_ref
    FROM
            catalog__icd10_cohort_block AS c,
            umls.icd10_chapter AS tree
    WHERE
        c.cui1 = tree.cui2


)
SELECT DISTINCT
    cui1,
    cui2,
    
        icd10_code,
        icd10_chapter,
        icd10_chapter_display,
    class_code,
    servicetype_display,
    age_at_visit,
    gender,
    race_display,
    ethnicity_display,
    subject_ref,
    encounter_ref
FROM cohort

-- ###########################################################

CREATE TABLE catalog__icd10_cohort_code AS
WITH
cohort AS (

    SELECT 
        tree.cui1,
        tree.cui2,
            tree.code AS icd10_code_parent,   -- parent
            concat('(', tree.code, ') ', tree.str) AS icd10_code_parent_display,
            c.code AS icd10_code_child,   -- child
            substring(c.code,1,5) as code_start,
            c.class_code,
            c.servicetype_display,
            c.age_at_visit,
            c.gender,
            c.race_display,
            c.ethnicity_display,
            c.subject_ref,
            c.encounter_ref
    FROM
            catalog__icd10_cohort AS c,
            umls.icd10_code AS tree


)
SELECT DISTINCT
    cui1,
    cui2,
    
        icd10_code_parent,
        icd10_code_parent_display,
        icd10_code_child,
    class_code,
    servicetype_display,
    age_at_visit,
    gender,
    race_display,
    ethnicity_display,
    subject_ref,
    encounter_ref
FROM cohort
    WHERE
        icd10_code_parent = code_start
