name: CI
on: [push]

# The goal here is to cancel older workflows when a PR is updated (because it's pointless work)
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  unittest:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[test]"
      - name: Create mock AWS credentials
        run: |
          mkdir ~/.aws && touch ~/.aws/credentials 
          echo -e "[test]\naws_access_key_id = test\naws_secret_access_key = test" > ~/.aws/credentials
      - name: Test with pytest
        run: |
          python -m pytest --cov-report xml --cov=cumulus_library tests
      - name: Log missing coverage
        run: |
          coverage report -m --skip-covered

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Run sqlfluff on jinja templates
        run: |
          sqlfluff lint
      - name: Run ruff
        if: success() || failure() # still run ruff if above checks fails
        run: |
          ruff check
          ruff format --check
